"""Add cascade delete for project-category relationship

Revision ID: 1f3b607c3784
Revises: 92adf2ca2da7
Create Date: 2025-09-05 14:46:34.751531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3b607c3784'
down_revision: Union[str, Sequence[str], None] = '92adf2ca2da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
