"""Rename project name column to project_name

Revision ID: f505ac37e931
Revises: ef3e624d3f67
Create Date: 2025-08-31 12:44:20.348377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f505ac37e931'
down_revision: Union[str, Sequence[str], None] = 'ef3e624d3f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For PostgreSQL, we need to rename the column properly
    op.alter_column('projects', 'name', new_column_name='project_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the column back
    op.alter_column('projects', 'project_name', new_column_name='name')
    # ### end Alembic commands ###
